name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, intl, openssl, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
    - name: Generate application key
      run: php artisan key:generate
    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Desplegar a través de FTP
    - name: Deploy to Hostinger via FTP
      uses: appleboy/ftp-action@v0.1.4
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./ # La carpeta que deseas subir (puedes cambiarla si es necesario)
        server-dir: /public_html/prueba # Directorio de destino en el servidor FTP
